### ISSUE TITLE
iOS 10 - App listing causes IDB to crash

### ISSUE THREAD

**Issue by zsolt-halo** [dmayer/idb#85] opened 2017-02-16 15:53 UTC
After jailbreaking my iOS 10.1 device with jalu102 jailbreak, i have successfully set up a pentesting environment on the phone.

IDB connects to the phone without any issues like it does on the iOS 9.x and 8.x devices but when i try to list the apps installed, IDB crashes.

Here is a log for further investigation:

`
[DEBUG] 2017-02-16 14:21:45 :: idb ::  Executing blocking SSH command: /bin/su mobile -c /usr/bin/uicache
[*] Retrieving list of applications...
[DEBUG] 2017-02-16 14:22:04 :: idb ::  App Dir: /private/var/containers/Bundle/Application/D5E6A26C-2A4B-4884-A790-C358220ED31F
[DEBUG] 2017-02-16 14:22:04 :: idb ::  Executing blocking SSH command: ls /private/var/containers/Bundle/Application/D5E6A26C-2A4B-4884-A790-C358220ED31F/*app/Info.plist
[INFO] 2017-02-16 14:22:04 :: idb ::  Info.plist found at /private/var/containers/Bundle/Application/D5E6A26C-2A4B-4884-A790-C358220ED31F/yalu102.app/Info.plist

**[INFO] 2017-02-16 14:22:04 :: idb ::  Parsing plist file..
[ERROR] 2017-02-16 14:22:04 :: idb ::  Error downloading file.**

/Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/plist4r-1.2.2/lib/plist4r/plist.rb:294:in 'open': No filename specified (RuntimeError)
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/plist4r-1.2.2/lib/plist4r.rb:34:in 'open'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/lib/ios8_last_launch_services_map_wrapper.rb:7:in 'initialize'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/lib/app.rb:29:in 'new'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/lib/app.rb:29:in 'initialize'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/app_list_dialog.rb:74:in 'new'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/app_list_dialog.rb:74:in 'block in refresh_app_list'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/app_list_dialog.rb:73:in 'each'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/app_list_dialog.rb:73:in 'refresh_app_list'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/app_list_dialog.rb:31:in 'initialize'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/global_app_details_group_box.rb:43:in 'new'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/gui/global_app_details_group_box.rb:43:in 'block in initialize'
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in 'call'
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in 'invoke'
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in 'qt_metacall'
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in 'method_missing'
	from /Users/zsh/.rvm/gems/ruby-2.1.8@global/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in 'exec'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/lib/idb.rb:278:in 'run'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/gems/idb-2.9.1/bin/idb:4:in '<top (required)>'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/bin/idb:23:in 'load'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/bin/idb:23:in '<main>'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in 'eval'
	from /Users/zsh/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in '<main>'
recv failed: Resource temporarily unavailable
`

**Comment by mavensecurity** [comment] 2017-05-18 00:59
I could not even successfully connect to my jailbroke 10.2 iPad Air 2.  After getting prompted for the root password and successfully entering it I saw idb console said:
Unsupported iOS version.

**Comment by Rick11929** [comment] 2017-06-14 12:57
Hi , i also saw the console said : Unsupported iOS version.

**Comment by zsolt-halo** [comment] 2017-06-14 14:18
I somehow circumvented this issue (Unsupported iOS version) by simply editing some code/configuration files locally but i cannot remember how i did that right now.
As soon as i find out i'll edit this comment.
The real problem here is what n0ttab0t mentioned.

**Comment by ngkogkos** [comment] 2017-06-16 18:26
Bumping this, idb solves hands and it would be good if someone can come up with a workaround.

**Comment by dmayer** [comment] 2017-07-22 21:27
Closing this one in favor of #91 where @jimmyjammz99 has identified the root cause. Will get an appropriate device and work on fixing it.

**Closed by dmayer** 2017-07-22 21:27 UTC
