### ISSUE TITLE
Error when Trying to get Applications

### ISSUE THREAD

**Issue by zerberos** [dmayer/idb#58] opened 2015-03-06 15:43 UTC
Hi

I get the following error when clicking on the Get Apps button:

idb-master/lib/lib/app.rb:24:in `initialize': undefined method`bundle_identifier' for nil:NilClass (NoMethodError)
/idb-master/lib/gui/app_list_dialog.rb:63:in `new'
/idb-master/lib/gui/app_list_dialog.rb:63:in`block in refresh_app_list'
/idb-master/lib/gui/app_list_dialog.rb:62:in `each'
idb-master/lib/gui/app_list_dialog.rb:62:in`refresh_app_list'
idb-master/lib/gui/app_list_dialog.rb:20:in `initialize'
idb-master/lib/gui/global_app_details_group_box.rb:43:in`new'
idb-master/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in`call'
gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:2454:in `invoke'
gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in`qt_metacall'
gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in `method_missing'
gems/qtbindings-4.8.6.0/lib/Qt/qtruby4.rb:479:in`exec'
gems/idb-2.6.2/bin/idb:4:in `<top (required)>'
bin/idb:23:in`load'
bin/idb:23:in `<main>'
.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`eval'
.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
recv failed: Resource temporarily unavailable

Tried many times, also rebooting, rebooting ipad etc.

Any idea about this?

Thanks!

**Comment by dmayer** [comment] 2015-03-06 17:29
Hi,

I have a few questions to narrow this down.
1) Is this the latest version of idb?
2) Which version of iOS are you running and has the device been upgraded from iOS to iOS 8?
3) Do you have any applications installed on the device? (See #55 )

Thanks,
Daniel

**Comment by zerberos** [comment] 2015-03-10 14:57
Hello Daniel

> 1) Is this the latest version of idb?
> 

I have downloaded and installed it on the day that I wrote this entry, so I guess it is the newest version
> 2) Which version of iOS are you running and has the device been upgraded from iOS to iOS 8?
> 

The iOS is 8.1.2

It was a fresh install, not an upgrade
> 3) Do you have any applications installed on the device? (See #55 <https://github.com/dmayer/idb/issues/55> )
> 
> 

Yes, there are several apps installed. They are also visible in the LastLaunchServicesMap.plist file.

It would be great if this problem could be fixed!

Thanks,
Andriu

**Comment by zerberos** [comment] 2015-03-13 19:27
Any idea yet?

Thanks

**Comment by zerberos** [comment] 2015-03-17 23:16
Hi

I am still waiting for some feedback - do you have an idea on how to fix this?

Thanks!

**Comment by dmayer** [comment] 2015-03-26 02:55
hey, really sorry, I had a lot of things going on. I am looking into this right now.

**Comment by dmayer** [comment] 2015-03-26 04:22
So, the problem is that the Info.plist file for one of the apps on your device either cannot be parsed or the bundle_identifier field for it cannot be found.  You could add a debug statement to lib/lib/app.rb to see for which app te parsing fails. If it is a public app, I'd like to install it locally and see if I can reproduce the bug.

**Comment by 3asm** [comment] 2015-03-29 14:29
I have the same issue, but it seems related to ssh forwarding not working:
[INFO] 2015-03-29 16:20:48 :: port_forward :: Setting up port forwarding...
[INFO] 2015-03-29 16:20:48 :: port_forward ::  - Forwarding remote:4711 -> localhost:4711
/var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/service/forward.rb:178:in `block in remote': remote forwarding request failed (Net::SSH::Exception)
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:505:in `call'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:505:in `request_failure'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /home/ola/MASA/ios/idb/lib/lib/ssh_port_forwarder.rb:31:in `start'
	from /home/ola/MASA/ios/idb/lib/lib/../helper/ssh_port_forwarder.rb:58:in `run'
	from /home/ola/MASA/ios/idb/lib/lib/../helper/ssh_port_forwarder.rb:63:in `<module:Idb>'
	from /home/ola/MASA/ios/idb/lib/lib/../helper/ssh_port_forwarder.rb:7:in `<main>'

**Comment by dmayer** [comment] 2015-03-29 20:14
Hi,

I honestly don’t think that is the case.  The calls to @plutil are in the same file:

      if RbConfig::CONFIG['host_os'] =~ /linux/
        `#{@plutil.realpath}  -i "#{@plist_file}" -o "#{@plist_file}"`
      else
        `#{@plutil.realpath} -convert xml1 "#{@plist_file}"`
      end

the  backpacks definitely run the command on the host. So lets figure out whats going on.

The forwarding error you mentioned in your first email may be due to the port being used already or a previous running instance of idb crashing and leaving stale “iproxy” processes behind. You can safely kill those processes.
Could you try removing all of the forwarding in the settings and see if idb then works properly?

Thanks,
Daniel

**Comment by n0x00** [comment] 2015-08-10 12:24
hey, hey, fresh install this week, new install of osx, I'm having the same issues - tool looks promising but haven't successfully loaded apps yet 

``O] 2015-08-10 13:21:25 :: idb ::  Parsing plist file..
[ERROR] 2015-08-10 13:21:25 :: idb ::  Info.plist not found.
[ERROR] 2015-08-10 13:21:25 :: idb ::  Info.plist not found.
[ERROR] 2015-08-10 13:21:25 :: idb ::  Error getting plist file .
[DEBUG] 2015-08-10 13:21:25 :: idb ::  Exception Details: undefined method `sub' for nil:NilClass.
[DEBUG] 2015-08-10 13:21:25 :: idb ::  Backtrace: /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/lib/app.rb:255:in `cache_file'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/lib/app.rb:271:in `parse_info_plist'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/lib/app.rb:17:in `initialize'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:76:in `new'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:76:in `block in refresh_app_list'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:75:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:75:in `refresh_app_list'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:33:in `initialize'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/global_app_details_group_box.rb:43:in `new'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
/usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
/usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
/usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/idb.rb:285:in `run'
./idb:4:in `<main>'.
/usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/lib/app.rb:24:in `initialize': undefined method `bundle_identifier' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:76:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:76:in `block in refresh_app_list'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:75:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:75:in `refresh_app_list'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/app_list_dialog.rb:33:in `initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/global_app_details_group_box.rb:43:in `new'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
	from /usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /usr/local/lib/ruby/gems/2.1.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
	from /usr/local/lib/ruby/gems/2.1.0/gems/idb-2.8/lib/idb.rb:285:in `run'
	from ./idb:4:in `<main>'
recv failed: Resource temporarily unavailable
``

**Comment by dannybrow** [comment] 2015-09-01 16:05
Hey I had this problem today. Turned out after a few extra debug lines it was just a messed up app. On my 8.1.3 device there was "3EF1BA8F-F005-4D54-A956-6AA1FDE7A444/UK.app/" that was empty. Not even sure yet what it was (kids use the device too :P so I'll blame them). But removed the folder and idb worked a treat as it has before.  If I get time - unlikely - I try and fork to put something in to help be less bothersome.

**Comment by dmayer** [comment] 2017-07-22 21:33
Some additional checks should be added to idb. I'll close this for now. If someone encounters similar issue, let me know and I will work on error checking code to overcome it.

**Closed by dmayer** 2017-07-22 21:33 UTC

**Comment by hpauta** [comment] 2018-10-04 18:57
Hi
My problem is one error about  'undefined method' ...imy platform is kali Linux 2017.3 and iOS 11

[INFO] 2018-10-04 20:52:39 :: idb ::  Parsing plist file..
[DEBUG] 2018-10-04 20:52:40 :: idb ::  Data Dir: {"$class"=>nil, "snapshots"=>nil, "identifier"=>nil}
[DEBUG] 2018-10-04 20:52:52 :: idb ::  Appending extension to AppIcon60x60
[DEBUG] 2018-10-04 20:52:52 :: idb ::  Now: AppIcon60x60*.png
[DEBUG] 2018-10-04 20:52:52 :: idb ::  Executing blocking SSH command: ls /private/var/containers/Bundle/Application/E690A21E-A817-40D9-B52B-DD65F2E569B5/*app/AppIcon60x60*.png
[INFO] 2018-10-04 20:52:55 :: idb ::  Icon found at /private/var/containers/Bundle/Application/E690A21E-A817-40D9-B52B-DD65F2E569B5/TestFlight.app/AppIcon60x60@2x.png
[INFO] 2018-10-04 20:52:55 :: idb ::  Locating application binary...
[DEBUG] 2018-10-04 20:52:56 :: idb ::  File not found: Net::SFTP::StatusException (2, "no such file")
[DEBUG] 2018-10-04 20:52:56 :: idb ::  File not found: Net::SFTP::StatusException (2, "no such file")
[DEBUG] 2018-10-04 20:52:56 :: idb ::  File not found: Net::SFTP::StatusException (2, "no such file")
[ERROR] 2018-10-04 20:52:56 :: idb ::  Cannot find ldid binary at /usr/bin/ldid
Traceback (most recent call last):
	26: from /var/lib/gems/2.5.0/bin/idb:23:in `<main>'
	25: from /var/lib/gems/2.5.0/bin/idb:23:in `load'
	24: from /root/movil/idb/bin/idb:4:in `<top (required)>'
	23: from /root/movil/idb/lib/idb.rb:278:in `run'
	22: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	21: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	20: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	19: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	18: from /root/movil/idb/lib/gui/global_app_details_group_box.rb:63:in `block in initialize'
	17: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `exec'
	16: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `method_missing'
	15: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:917:in `qt_metacall'
	14: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	13: from /root/movil/idb/lib/gui/app_list_dialog.rb:24:in `block in initialize'
	12: from /root/movil/idb/lib/gui/app_list_dialog.rb:24:in `method_missing'
	11: from /root/movil/idb/lib/gui/app_list_dialog.rb:24:in `qt_metacall'
	10: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	 9: from /root/movil/idb/lib/gui/global_app_details_group_box.rb:61:in `block (2 levels) in initialize'
	 8: from /root/movil/idb/lib/gui/global_app_details_group_box.rb:61:in `app_changed'
	 7: from /root/movil/idb/lib/gui/global_app_details_group_box.rb:61:in `qt_metacall'
	 6: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	 5: from /root/movil/idb/lib/idb.rb:122:in `block in init_ui'
	 4: from /root/movil/idb/lib/gui/main_tab_widget.rb:159:in `app_changed'
	 3: from /root/movil/idb/lib/gui/main_tab_widget.rb:95:in `enableLocalStorage'
	 2: from /root/movil/idb/lib/gui/local_storage_tab_widget.rb:25:in `setup'
	 1: from /root/movil/idb/lib/gui/plist_file_widget.rb:52:in `setup'
/root/movil/idb/lib/gui/default_protection_class_group_widget.rb:23:in `update': undefined method `each' for "":String (NoMethodError)
